version: '3.7'

services:
  app:
    tty: true
    restart: always
    env_file: ./.env
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: dev
    volumes:
      - ../app:/app:delegated
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - mysql
    networks:
      - bridge

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - bridge
networks:
  bridge:

volumes:
  db-data:
