name: CD

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy to vm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          key: ${{ secrets.LINODE_SSHKEY }}
          script: |
            cd /var/www/html/ec-shop
            git checkout .
            git reset --hard
            git pull
            docker-compose -f ./docker/docker-compose.yml --env-file ./docker/.env up -d --build
